from datetime import datetime, timedelta, timezone

from sytdl.service import SonarrYTDLService


class RecordingSonarr:
    def __init__(self, episodes):
        self.episodes = episodes
        self.rescanned = []

    def get_series(self):
        return [
            {
                "id": 7,
                "title": "Test Show",
                "monitored": True,
                "path": "/tv/Test Show",
            }
        ]

    def get_episodes(self, _series_id):
        return self.episodes

    def rescan_series(self, series_id):
        self.rescanned.append(series_id)


class RecordingDownloader:
    def __init__(self, result=1):
        self.result = result
        self.calls = []

    def download_series(self, series, episodes):
        self.calls.append((series, episodes))
        return self.result


def test_run_normalizes_config_filters_utc_airdates_and_rescans(tmp_path):
    now = datetime.now(timezone.utc)
    base_episode = {
        "seriesId": 7,
        "monitored": True,
        "hasFile": False,
        "seasonNumber": 1,
    }
    sonarr = RecordingSonarr(
        [
            {
                **base_episode,
                "id": 1,
                "title": "Aired Episode - #42",
                "episodeNumber": 1,
                "airDateUtc": (now - timedelta(minutes=1))
                .isoformat(timespec="milliseconds")
                .replace("+00:00", "Z"),
            },
            {
                **base_episode,
                "id": 2,
                "title": "Future Episode",
                "episodeNumber": 2,
                "airDateUtc": (now + timedelta(hours=1))
                .isoformat()
                    .replace("+00:00", "Z"),
            },
            {
                **base_episode,
                "id": 3,
                "title": "Already Downloaded",
                "episodeNumber": 3,
                "hasFile": True,
                "airDateUtc": (now - timedelta(days=1)).isoformat(),
            },
            {
                **base_episode,
                "id": 4,
                "title": "Not Monitored",
                "episodeNumber": 4,
                "monitored": False,
                "airDateUtc": (now - timedelta(days=1)).isoformat(),
            },
            {
                **base_episode,
                "id": 5,
                "title": "Date Not Announced",
                "episodeNumber": 5,
                "airDateUtc": None,
            },
        ]
    )
    downloader = RecordingDownloader()
    config_path = tmp_path / "config.yml"
    config_path.write_text(
        """
sonarrytdl:
  cron: "*/15 * * * *"
  debug: false
ytdl:
  default_format: best
series:
  - title: Test Show
    url: https://example.test/list
    playlistreverse: false
    regex:
      sonarr:
        match: " - #[0-9]+$"
        replace: ""
    subtitles:
      languages: [en, de]
      autogenerated: true
""".lstrip(),
        encoding="utf-8",
    )
    service = SonarrYTDLService(
        config_file=config_path,
        sonarr_client=sonarr,
        downloader=downloader,
    )

    assert service.run() == 1
    assert sonarr.rescanned == [7]
    series, episodes = downloader.calls[0]
    assert series["playlistreverse"] is False
    assert series["subtitles_autogenerated"] is True
    assert series["subtitles_languages"] == ["en", "de"]
    assert [episode["title"] for episode in episodes] == ["Aired Episode"]


def test_failed_download_does_not_trigger_sonarr_rescan():
    now = datetime.now(timezone.utc)
    sonarr = RecordingSonarr(
        [
            {
                "id": 1,
                "seriesId": 7,
                "title": "Episode",
                "monitored": True,
                "hasFile": False,
                "seasonNumber": 1,
                "episodeNumber": 1,
                "airDateUtc": (now - timedelta(hours=1)).isoformat(),
            }
        ]
    )
    downloader = RecordingDownloader(result=0)
    cfg = {
        "sonarrytdl": {"cron": "* * * * *"},
        "ytdl": {"default_format": "best"},
        "series": [
            {"title": "Test Show", "url": "https://example.test/list"}
        ],
    }
    service = SonarrYTDLService(
        cfg=cfg, sonarr_client=sonarr, downloader=downloader
    )

    assert service.run() == 0
    assert sonarr.rescanned == []


def test_release_offset_can_make_an_early_episode_eligible():
    now = datetime.now(timezone.utc)
    sonarr = RecordingSonarr(
        [
            {
                "id": 1,
                "seriesId": 7,
                "title": "Members Release",
                "monitored": True,
                "hasFile": False,
                "seasonNumber": 1,
                "episodeNumber": 1,
                "airDateUtc": (now + timedelta(hours=1)).isoformat(),
            }
        ]
    )
    downloader = RecordingDownloader()
    cfg = {
        "sonarrytdl": {"cron": "* * * * *"},
        "ytdl": {"default_format": "best"},
        "series": [
            {
                "title": "Test Show",
                "url": "https://example.test/list",
                "offset": {"hours": -2},
            }
        ],
    }
    service = SonarrYTDLService(
        cfg=cfg, sonarr_client=sonarr, downloader=downloader
    )

    assert service.run() == 1
    assert downloader.calls[0][1][0]["title"] == "Members Release"
    assert sonarr.rescanned == [7]


def test_no_eligible_episodes_skips_ytdlp_entirely():
    now = datetime.now(timezone.utc)
    sonarr = RecordingSonarr(
        [
            {
                "id": 1,
                "seriesId": 7,
                "title": "Next Week",
                "monitored": True,
                "hasFile": False,
                "seasonNumber": 1,
                "episodeNumber": 1,
                "airDateUtc": (now + timedelta(days=7)).isoformat(),
            }
        ]
    )
    downloader = RecordingDownloader()
    cfg = {
        "sonarrytdl": {"cron": "* * * * *"},
        "ytdl": {"default_format": "best"},
        "series": [
            {"title": "Test Show", "url": "https://example.test/list"}
        ],
    }
    service = SonarrYTDLService(
        cfg=cfg, sonarr_client=sonarr, downloader=downloader
    )

    assert service.run() == 0
    assert downloader.calls == []
    assert sonarr.rescanned == []
