from sytdl.downloader import EpisodeDownloader


class FakeYoutubeDL:
    def __init__(self, factory, options):
        self.factory = factory
        self.options = options

    def __enter__(self):
        self.factory.seen_options.append(self.options)
        return self

    def __exit__(self, *_args):
        return False

    def extract_info(self, _playlist, download=False):
        assert download is False
        self.factory.extract_calls += 1
        return self.factory.extract_result

    def download(self, urls):
        self.factory.downloaded_urls.extend(urls)
        return self.factory.download_status


class FakeYoutubeDLFactory:
    def __init__(self, extract_result=None, download_status=0):
        self.extract_result = extract_result
        self.download_status = download_status
        self.seen_options = []
        self.downloaded_urls = []
        self.extract_calls = 0

    def __call__(self, options):
        return FakeYoutubeDL(self, options)


def make_downloader(
    factory, config_file="/config/config.yml", sonarr_root="/media"
):
    return EpisodeDownloader(
        "best",
        config_file,
        ytdl_factory=factory,
        sonarr_root=sonarr_root,
    )


def make_series(**overrides):
    series = {
        "id": 7,
        "title": "Test Show",
        "url": "https://example.test/list",
        "path": "/tv/Test Show",
        "playlistreverse": True,
        "subtitles": False,
    }
    series.update(overrides)
    return series


def make_episode():
    return {
        "seriesId": 7,
        "title": "Episode 42",
        "seasonNumber": 1,
        "episodeNumber": 2,
    }


def test_matching_applies_site_cleanup_and_handles_unavailable_entries():
    factory = FakeYoutubeDLFactory(
        {
            "entries": [
                None,
                {"title": None, "url": "private"},
                {
                    "title": "Rock & Roll Johns Cut [Official Upload]",
                    "webpage_url": "https://example.test/watch/42",
                },
            ]
        }
    )
    downloader = make_downloader(factory)
    series = make_series(
        site_regex_match=r" \[Official Upload\]$", site_regex_replace=""
    )
    episode = make_episode()
    episode["title"] = "Rock and Roll: John's Cut!"

    assert downloader.find_episode(series, episode) == (
        "https://example.test/watch/42"
    )


def test_matching_does_not_confuse_shorter_numbered_episode_titles():
    factory = FakeYoutubeDLFactory(
        {
            "entries": [
                {
                    "title": "Episode 420",
                    "webpage_url": "https://example.test/watch/420",
                },
                {
                    "title": "Episode 42",
                    "webpage_url": "https://example.test/watch/42",
                },
            ]
        }
    )
    downloader = make_downloader(factory)

    assert downloader.find_episode(make_series(), make_episode()) == (
        "https://example.test/watch/42"
    )


def test_failed_ytdlp_status_is_not_treated_as_a_download():
    factory = FakeYoutubeDLFactory(download_status=1)
    downloader = make_downloader(factory)

    succeeded = downloader.download_episode(
        make_series(), make_episode(), "https://example.test/watch/42"
    )

    assert succeeded is False
    assert factory.downloaded_urls == ["https://example.test/watch/42"]
    options = factory.seen_options[0]
    assert options["merge_output_format"] == "mkv"
    assert "merge-output-format" not in options
    assert options["outtmpl"].startswith("/media/tv/Test Show/Season 1/")


def test_series_download_counts_only_successfully_matched_episodes():
    factory = FakeYoutubeDLFactory(
        {
            "entries": [
                {
                    "title": "Episode 42",
                    "webpage_url": "https://example.test/watch/42",
                }
            ]
        }
    )
    downloader = make_downloader(factory)
    missing_episode = {
        **make_episode(),
        "title": "Episode 43",
        "episodeNumber": 3,
    }

    downloaded = downloader.download_series(
        make_series(), [make_episode(), missing_episode]
    )

    assert downloaded == 1
    assert factory.downloaded_urls == ["https://example.test/watch/42"]
    assert factory.extract_calls == 1


def test_download_honors_relative_cookies_subtitles_and_specials_path(tmp_path):
    cookies = tmp_path / "youtube_cookies.txt"
    cookies.write_text("# Netscape HTTP Cookie File\n", encoding="utf-8")
    factory = FakeYoutubeDLFactory()
    downloader = make_downloader(factory, config_file=tmp_path / "config.yml")
    series = make_series(
        cookies_file="youtube_cookies.txt",
        format="bestvideo+bestaudio",
        subtitles=True,
        subtitles_languages=["en", "de"],
        subtitles_autogenerated=True,
    )
    episode = {**make_episode(), "seasonNumber": 0}

    assert downloader.download_episode(
        series, episode, "https://example.test/watch/42"
    )

    options = factory.seen_options[0]
    assert options["cookiefile"] == str(cookies)
    assert options["format"] == "bestvideo+bestaudio"
    assert options["writesubtitles"] is True
    assert options["writeautomaticsub"] is True
    assert options["subtitleslangs"] == ["en", "de"]
    assert "/Specials/" in options["outtmpl"]
    assert [processor["key"] for processor in options["postprocessors"]] == [
        "FFmpegVideoRemuxer",
        "FFmpegSubtitlesConvertor",
        "FFmpegEmbedSubtitle",
    ]
