import logging
import re
from datetime import datetime, timezone

from .config import ConfigError, as_bool, get_config_path, load_config
from .downloader import EpisodeDownloader
from .media import offset_air_date, parse_air_date
from .sonarr import SonarrClient


logger = logging.getLogger("sonarr_youtubedl")


class SonarrYTDLService(object):
    """Coordinate config, Sonarr episode state, and yt-dlp downloads."""

    def __init__(
        self,
        cfg=None,
        config_file=None,
        debug_override=False,
        sonarr_client=None,
        downloader=None,
    ):
        cfg = cfg if cfg is not None else load_config(config_file)
        self.config_file = get_config_path(config_file)

        app_cfg = cfg.get("sonarrytdl", {})
        if not isinstance(app_cfg, dict):
            raise ConfigError("sonarrytdl must be a YAML mapping")
        self.debug = debug_override or as_bool(app_cfg.get("debug"), False)
        if self.debug:
            logger.setLevel(logging.DEBUG)
            for handler in logger.handlers:
                handler.setLevel(logging.DEBUG)
            logger.debug("Debugging enabled")

        self.sonarr = (
            sonarr_client
            if sonarr_client is not None
            else SonarrClient.from_config(cfg.get("sonarr"))
        )

        ytdl_cfg = cfg.get("ytdl")
        if not isinstance(ytdl_cfg, dict) or not ytdl_cfg.get("default_format"):
            raise ConfigError("ytdl.default_format is required")
        self.default_format = str(ytdl_cfg["default_format"])

        series_cfg = cfg.get("series")
        if not isinstance(series_cfg, list):
            raise ConfigError("series must be a YAML list")
        self.series_config = self._validate_series_config(series_cfg)
        self.downloader = (
            downloader
            if downloader is not None
            else EpisodeDownloader(self.default_format, self.config_file, self.debug)
        )

    @staticmethod
    def _validate_series_config(series_cfg):
        validated = []
        titles = set()
        for index, item in enumerate(series_cfg, start=1):
            if not isinstance(item, dict):
                raise ConfigError("series item {} must be a YAML mapping".format(index))
            if not item.get("title") or not item.get("url"):
                raise ConfigError(
                    "series item {} requires both title and url".format(index)
                )
            title = str(item["title"])
            if title in titles:
                raise ConfigError("Duplicate series title in config: {}".format(title))
            titles.add(title)

            regex_cfg = item.get("regex", {})
            if not isinstance(regex_cfg, dict):
                raise ConfigError("regex for {} must be a YAML mapping".format(title))
            for source in ("sonarr", "site"):
                rule = regex_cfg.get(source)
                if rule is None:
                    continue
                if not isinstance(rule, dict) or "match" not in rule:
                    raise ConfigError(
                        "regex.{} for {} requires a match value".format(source, title)
                    )
                try:
                    re.compile(str(rule["match"]))
                except re.error as exc:
                    raise ConfigError(
                        "Invalid regex.{} match for {}: {}".format(source, title, exc)
                    ) from exc
            validated.append(item)
        return validated

    def matched_series(self):
        """Match configured titles to Sonarr v4 series."""
        sonarr_series = self.sonarr.get_series()
        if not isinstance(sonarr_series, list):
            raise RuntimeError("Sonarr returned an invalid response for /series")

        wanted = {str(item["title"]): item for item in self.series_config}
        matched = []
        found_titles = set()

        for source_series in sonarr_series:
            title = source_series.get("title")
            if title not in wanted:
                continue
            found_titles.add(title)
            configured = wanted[title]
            series = dict(source_series)
            series.update(
                {
                    "url": str(configured["url"]),
                    "playlistreverse": as_bool(
                        configured.get("playlistreverse"), True
                    ),
                    "subtitles": False,
                    "subtitles_languages": ["en"],
                    "subtitles_autogenerated": False,
                }
            )

            regex_cfg = configured.get("regex", {})
            for source in ("sonarr", "site"):
                rule = regex_cfg.get(source)
                if rule:
                    series["{}_regex_match".format(source)] = str(rule["match"])
                    series["{}_regex_replace".format(source)] = str(
                        rule.get("replace", "")
                    )
            for option in ("offset", "cookies_file", "format"):
                if option in configured:
                    series[option] = configured[option]

            subtitles = configured.get("subtitles")
            if subtitles is not None:
                if not isinstance(subtitles, dict):
                    raise ConfigError(
                        "subtitles for {} must be a YAML mapping".format(title)
                    )
                languages = subtitles.get("languages", ["en"])
                if isinstance(languages, str):
                    languages = [languages]
                if not isinstance(languages, list) or not languages:
                    raise ConfigError(
                        "subtitles.languages for {} must be a non-empty list".format(
                            title
                        )
                    )
                series["subtitles"] = True
                series["subtitles_languages"] = [str(value) for value in languages]
                series["subtitles_autogenerated"] = as_bool(
                    subtitles.get("autogenerated"), False
                )

            if not series.get("monitored", False):
                logger.warning("%s is not currently monitored in Sonarr", title)
            matched.append(series)

        for missing_title in sorted(set(wanted) - found_titles):
            logger.warning("Configured series was not found in Sonarr: %s", missing_title)
        return matched

    def wanted_episodes(self, series):
        """Return aired, monitored, missing episodes and prune idle series."""
        needed = []
        active_ids = set()
        current_time = datetime.now(timezone.utc)

        for item in series:
            episodes = self.sonarr.get_episodes(item["id"])
            if not isinstance(episodes, list):
                raise RuntimeError(
                    "Sonarr returned an invalid episode response for {}".format(
                        item["title"]
                    )
                )
            series_episodes = []
            for source_episode in episodes:
                if not source_episode.get("monitored", False):
                    continue
                if source_episode.get("hasFile", False):
                    continue
                episode_date = parse_air_date(source_episode.get("airDateUtc"))
                if episode_date is None:
                    logger.debug(
                        "Skipping %s because Sonarr has no airDateUtc",
                        source_episode.get("title", "unknown episode"),
                    )
                    continue
                if "offset" in item:
                    episode_date = offset_air_date(episode_date, item["offset"])
                if episode_date > current_time:
                    continue

                episode = dict(source_episode)
                if "sonarr_regex_match" in item:
                    episode["title"] = re.sub(
                        item["sonarr_regex_match"],
                        item["sonarr_regex_replace"],
                        str(episode.get("title", "")),
                    )
                if not episode.get("title"):
                    logger.warning(
                        "Skipping S%02dE%02d because its title is empty",
                        episode.get("seasonNumber", 0),
                        episode.get("episodeNumber", 0),
                    )
                    continue
                series_episodes.append(episode)

            if series_episodes:
                active_ids.add(item["id"])
                needed.extend(series_episodes)
                logger.info(
                    "%s missing %d aired episode(s)",
                    item["title"],
                    len(series_episodes),
                )
                for index, episode in enumerate(series_episodes, start=1):
                    logger.info(
                        "  %d: %s - %s", index, item["title"], episode["title"]
                    )
            else:
                logger.info("%s has no aired episodes needing download", item["title"])

        series[:] = [item for item in series if item["id"] in active_ids]
        return needed

    def download(self, series, episodes):
        if not series:
            logger.info("Nothing to process")
            return 0

        logger.info("Processing wanted downloads")
        total = 0
        for item in series:
            logger.info("  %s:", item["title"])
            downloaded = self.downloader.download_series(item, episodes)
            total += downloaded
            if downloaded:
                self.sonarr.rescan_series(item["id"])
        return total

    def run(self):
        series = self.matched_series()
        episodes = self.wanted_episodes(series)
        return self.download(series, episodes)
